### PR TITLE
from #57, add source setup.bash is added to .basharc

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/317/

**Build Log**
*last 10 lines*

 ```
[...truncated 21749 lines...]
1
+ umount /tmp/mount.55203
umount: /tmp/mount.55203: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: k-okada@jsk.t.u-tokyo.ac.jp
Setting status of 9610ae7a825517836fdaa1efeb015ad3b78524a6 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/317/ and message: Merged build finished.
```

Test FAILed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/318/

**Build Log**
*last 10 lines*

 ```
[...truncated 21628 lines...]
+ qemu-system-x86_64 -monitor telnet:0.0.0.0:1025,server,nowait -usb -cdrom hydro -boot d -m 4096 -enable-kvm -vga std
qemu-system-x86_64: -cdrom hydro: could not open disk image hydro: No such file or directory
+ exec
./00-check-cd.sh: connect: Connection refused
./00-check-cd.sh: line 27: /dev/tcp/localhost/1025: Connection refused
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: k-okada@jsk.t.u-tokyo.ac.jp
Setting status of 54791428f6684537c86bb97e0dad01c502af778a to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/318/ and message: Merged build finished.
```

Test FAILed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/319/

**Build Log**
*last 10 lines*

 ```
[...truncated 21684 lines...]
+ qemu-system-x86_64 -monitor telnet:0.0.0.0:1025,server,nowait -usb -cdrom 12.04 -boot d -m 4096 -enable-kvm -vga std
qemu-system-x86_64: -cdrom 12.04: could not open disk image 12.04: No such file or directory
+ exec
./00-check-cd.sh: connect: Connection refused
./00-check-cd.sh: line 27: /dev/tcp/localhost/1025: Connection refused
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: k-okada@jsk.t.u-tokyo.ac.jp
Setting status of 06fe97852ad5edc37df90351918949bdc4b176a9 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/319/ and message: Merged build finished.
```

Test FAILed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/320/

**Build Log**
*last 10 lines*

 ```
[...truncated 21906 lines...]
inet_listen_opts: FAILED
chardev: opening backend "socket" failed: Address already in use
+ exec
./00-check-cd.sh: connect: Connection refused
./00-check-cd.sh: line 26: /dev/tcp/localhost/1025: Connection refused
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: k-okada@jsk.t.u-tokyo.ac.jp
Setting status of cc75f007d421417c86892f8f1ab60afd8efc13b9 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/320/ and message: Merged build finished.
```

Test FAILed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/321/

**Build Log**
*last 10 lines*

 ```
[...truncated 21872 lines...]
inet_listen_opts: FAILED
chardev: opening backend "socket" failed: Address already in use
+ exec
./00-check-cd.sh: connect: Connection refused
./00-check-cd.sh: line 26: /dev/tcp/localhost/1025: Connection refused
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: k-okada@jsk.t.u-tokyo.ac.jp
Setting status of f9dfb035352001c06895d78ff3073043fb18fbd8 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/321/ and message: Merged build finished.
```

Test FAILed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/322/

**Build Log**
*last 10 lines*

 ```
[...truncated 21911 lines...]
1
+ grep -c '=== NG ===' /tmp/mount.25038/result.txt
1
+ umount /tmp/mount.25038
+ exit 1
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: k-okada@jsk.t.u-tokyo.ac.jp
Setting status of 0c9f422cf759947367d905974b929af881296fe7 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/322/ and message: Merged build finished.
```

Test FAILed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/323/

**Build Log**
*last 10 lines*

 ```
[...truncated 21976 lines...]
1
+ grep -c '=== NG ===' /tmp/mount.10942/result.txt
1
+ umount /tmp/mount.10942
+ exit 1
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: k-okada@jsk.t.u-tokyo.ac.jp
Setting status of bcbe850c0433a6911c5cdd27568420bb9dce929b to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/323/ and message: Merged build finished.
```

Test FAILed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/325/
Test PASSed.

**Comment by 534o** [comment]
Memo

We need to comment out following copy section not to remove configured resolv.conf
https://github.com/nsisodiya/Ubuntu-Max/blob/master/uck-resolv.conf.patch

**Pull request merged**
