### PR TITLE
Add source of TORK's workshop

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by k-okada** [comment]
Can one of the admins verify this patch?

**Comment by k-okada** [comment]
Can one of the admins verify this patch?

**Comment by 130s** [comment]
Re-triggering.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/378/
Test PASSed.

**Pull request merged**
