### PR TITLE
add baxter/beginner/intermediate users and dev source is under his home directory

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/297/

**Build Log**
*last 10 lines*

 ```
[...truncated 4315 lines...]
Unmounting /var/lib/jenkins/tmp/remaster-root/sys...
Unmounting /var/lib/jenkins/tmp/remaster-root/run...
Unmounting /var/lib/jenkins/tmp/remaster-root/root...
Unmounting /var/lib/jenkins/tmp/remaster-root/proc...
Unmounting /var/lib/jenkins/tmp/remaster-root/dev/pts...
Cleaning up temporary directories...
Build step 'Execute shell' marked build as failure
Archiving artifacts
Setting status of 9f27cecb74fe1bc6edb7a6b47e03e449de0a23c6 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/297/ and message: Merged build finished.
```

Test FAILed.

**Comment by 130s** [comment]
How can we restart this test on jenkins?

**Comment by k-okada** [comment]
I think we have to resolve conflict

**Comment by 130s** [comment]
I see. Then closing in favor of https://github.com/tork-a/live-cd/pull/68

**Pull request closed without merging**
