### PR TITLE
[00-create-cd.sh] enable ENABLE_LOCAL_REPO

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/350/

**Build Log**
*last 10 lines*

 ```
[...truncated 24805 lines...]
inet_listen_opts: FAILED
chardev: opening backend "socket" failed: Address already in use
+ exec
./00-check-cd.sh: connect: Connection refused
./00-check-cd.sh: line 26: /dev/tcp/localhost/1025: Connection refused
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: k-okada@jsk.t.u-tokyo.ac.jp
Setting status of 684b7208fd50941f53ccec88dd43e88e2cca1224 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/350/ and message: Merged build finished.
```

Test FAILed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/351/

**Build Log**
*last 10 lines*

 ```
[...truncated 110 lines...]
  linux-image-3.2.0-89-generic linux-image-3.2.0-87-generic
  linux-image-3.2.0-88-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
+ sudo rm -fr /var/lib/jenkins/tmp/remaster-apt-cache /var/lib/jenkins/tmp/remaster-iso /var/lib/jenkins/tmp/remaster-new-files /var/lib/jenkins/tmp/remaster-root /var/lib/jenkins/tmp/remaster-root-home
Build was aborted
Aborted by k-okada
Archiving artifacts
Setting status of 935832c21126f28c98ba79224f46425c6557e565 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/351/ and message: Merged build finished.
```

Test FAILed.

**Comment by 130s** [comment]
Test is aborted without clear clue.
```
Use 'apt-get autoremove' to remove them. 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded. + sudo rm -fr /var/lib/jenkins/tmp/remaster-apt-cache /var/lib/jenkins/tmp/remaster-iso /var/lib/jenkins/tmp/remaster-new-files /var/lib/jenkins/tmp/remaster-root /var/lib/jenkins/tmp/remaster-root-home Build was aborted Aborted by k-okada Archiving artifacts Setting status of 935832c21126f28c98ba79224f46425c6557e565 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/351/ and message: Merged build finished. Refer to this link for build results (access rights to CI server needed): http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/351/ **Build Log** *last 10 lines* ``` [...truncated 110 lines...] linux-image-3.2.0-89-generic linux-image-3.2.0-87-generic linux-image-3.2.0-88-generic Use 'apt-get autoremove' to remove them. 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded. + sudo rm -fr /var/lib/jenkins/tmp/remaster-apt-cache /var/lib/jenkins/tmp/remaster-iso /var/lib/jenkins/tmp/remaster-new-files /var/lib/jenkins/tmp/remaster-root /var/lib/jenkins/tmp/remaster-root-home Build was aborted Aborted by k-okada Archiving artifacts Setting status of 935832c21126f28c98ba79224f46425c6557e565 to FAILURE with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/351/ and message: Merged build finished. ``` Test FAILed. Finished: ABORTED
```

**Comment by k-okada** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/352/

--
◉ Kei Okada

**Comment by k-okada** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/353/

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/353/
Test PASSed.

**Comment by 130s** [comment]
@k-okada ありがとうございました．

一発でテストが通るようになることはなく，時間が経てば通るようなものなのでしょうか？

**Comment by k-okada** [comment]
間違えていた，気が変わった，等々で何回か直しました．

--
◉ Kei Okada


2015-09-07 18:40 GMT+09:00 Isaac I.Y. Saito <notifications@github.com>:

**Pull request merged**
