### PR TITLE
readme some clarification

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by k-okada** [comment]
Can one of the admins verify this patch?

**Comment by k-okada** [comment]
Can one of the admins verify this patch?

**Comment by 130s** [comment]
Looks like build is green but CircleCI is failing because the tests are missing in this repo?

**Comment by 130s** [comment]
Or maybe we're missing circleci.yml. Need https://github.com/tork-a/live-cd/pull/71

**Comment by k-okada** [comment]
Can one of the admins verify this patch?

**Comment by k-okada** [comment]
Can one of the admins verify this patch?

**Comment by k-okada** [comment]
circleci is not working right now, I removed that from webohook, so please re-commit this issue to trigger jenkins again.

**Comment by 130s** [comment]
@k-okada hmm looks like this (and #75) is not associated back with jenkins. Do you know anything about this?

**Comment by k-okada** [comment]
GitHub Pull Request Builder has property named  	Admin list and this plugin only runs jenkins test from admin patch. so far we only listed k-okada, so add 130s and tork-a. 

please try again

**Pull request closed without merging**
